language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
#  - osx
script:
  - ./test.sh
env:
 global:
   - RUST_BACKTRACE=full
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
    - binutils-dev
    - libunwind8-dev
sudo: required
