[package]
name = "honggfuzz"
version = "0.1.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]
license = "MIT/Apache-2.0/Unlicense/WTFPL"
repository = "https://github.com/PaulGrandperrin/honggfuzz-rs"
documentation = "https://github.com/PaulGrandperrin/honggfuzz-rs/blob/master/README.md"
homepage = "https://github.com/PaulGrandperrin/honggfuzz-rs/blob/master/README.md"
readme = "README.md"
keywords = ["fuzzing", "honggfuzz"]
description = """
Fuzz your Rust code with Honggfuzz !
"""

[dependencies]
