[package]
name = "honggfuzz"
version = "0.2.1"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]
license = "MIT/Apache-2.0/Unlicense/WTFPL"
repository = "https://github.com/PaulGrandperrin/honggfuzz-rs"
documentation = "https://docs.rs/honggfuzz"
homepage = "https://github.com/PaulGrandperrin/honggfuzz-rs/blob/master/README.md"
readme = "README.md"
keywords = ["fuzzing", "honggfuzz"]
description = """
Fuzz your Rust code with Honggfuzz !
"""

exclude = [
	"/honggfuzz/examples/**",
	"/honggfuzz/hfuzz_cc/**",
	"/honggfuzz/screenshot-honggfuzz-1.png",
	"/honggfuzz/third_party/**",
	"/honggfuzz/includes/**",
]

[badges]
travis-ci = { repository = "PaulGrandperrin/honggfuzz-rs", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
